[package]
name = "the-repo-name"
version = "0.1.0"
edition = "2021"
authors = ["Manuel Holtgrewe <manuel.holtgrewe@bih-charite.de>"]
description = "Rust template repository"
license = "Apache-2.0"
homepage = "https://github.com/bihealth/the-repo-name"
readme = "README.md"

[lib]
name = "the_repo_name"
path = "src/lib.rs"

[dependencies]
thiserror = "1.0"
tracing = "0.1"

[dev-dependencies]
anyhow = "1.0"
clap = { version = "4.1", features = ["derive", "env"] }
clap-verbosity-flag = {version = "2.0"}
env_logger = "0.10"
pretty_assertions = "1.3"
temp_testdir = "0.2"
test-log = "0.2"
tracing-subscriber = {version = "0.3" }
